name: Terraform Apply

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::115717304992:role/github-actions-terraform-role
          aws-region: ap-south-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.6
          terraform_wrapper: false

      - run: terraform init -no-color
      - run: terraform validate -no-color

      - name: Terraform Apply Debug
        run: |
          set +e
          terraform apply -auto-approve -no-color 2>&1 | tee terraform.log
          EXIT_CODE=${PIPESTATUS[0]}
          echo "Terraform exit code: $EXIT_CODE"
          grep -i "error:" terraform.log || true
          exit $EXIT_CODE